const SET_RECIPES = "SET_RECIPES";
const SET_LOADING = "SET_LOADING";
const SET_SINGLE_RECIPE = "SET_SINGLE_RECIPE";
const SET_SINGLE_RECIPE_LOADING = "SET_SINGLE_RECIPE_LOADING";
const SET_RANDOM_RECIPE = "SET_RANDOM_RECIPE";
const SET_MODAL_OPEN = "SET_MODAL_OPEN";
const SET_MODAL_CLOSE = "SET_MODAL_CLOSE";
const SET_UNIQUE_CATEGORY = "SET_UNIQUE_CATEGORY";
const SET_TOGGLE_SORT = "SET_TOGGLE_SORT";
const SET_VIEW = "SET_VIEW";
const SET_STYLE_FILTER = "SET_STYLE_FILTER";
const SET_SORT_RECIPES = "SET_SORT_RECIPES";
const SET_TOGGLE_SORT_ORDER = "SET_TOGGLE_SORT_ORDER";
const SET_SEARCH = "SET_SEARCH";

export {
  SET_RECIPES,
  SET_LOADING,
  SET_SINGLE_RECIPE,
  SET_SINGLE_RECIPE_LOADING,
  SET_RANDOM_RECIPE,
  SET_MODAL_OPEN,
  SET_MODAL_CLOSE,
  SET_UNIQUE_CATEGORY,
  SET_TOGGLE_SORT,
  SET_TOGGLE_SORT_ORDER,
  SET_VIEW,
  SET_STYLE_FILTER,
  SET_SORT_RECIPES,
  SET_SEARCH,
};
